### ISSUE TITLE
About comparing supervised vs Moco&CMC

### ISSUE THREAD

**Issue by jychoi118** [WangYueFt/rfs#2]
In table 3 of your paper, "supervised" model uses ResNet-50 as backbone, with accuracy of 73.81% in miniImagenet 5-way. However, "Ours-simple" model in table 1 with ResNet-12 reports 79.64%. 

But as you mentioned in section 4.9, results should improve with better backbone networks.

Can you explain why the accuracy with ResNet-50 is lower than ResNet-12?

**Comment by HobbitLong** [comment]
Hi, @jychoi118,

I think in general it's true that better models lead to higher accuracy, and this is true for the progress of few-shot recognition in past years.

For the ResNet-50 on MiniImageNet, I feel it might be an overkill for such as small data set, and it might be related to "Deep Double Descent" phenomenon (see [here](https://arxiv.org/abs/1912.02292)). 

One potential solution to fix this might be using more stronger data augmentation for ResNet-50, which should be fun to see but is not the point of the project.
