### ISSUE TITLE
the difference accuracy with baseline 

### ISSUE THREAD

**Issue by George0726** [WangYueFt/rfs#30]
Hi authors,
Thanks for releasing your codes! 
Can I ask a question what the difference between your methods from "A Closer look at few-shot learning"? The two methods are both train pre-trained models and use the representation to do few-shot testing (ignore distillation part). 

The accuracy is quite different. "a closer look" for resnet18 baseline miniImagenet: 42.11±0.71, while your paper resnet12 62.02/ resnet18 57.56.
(the difference between the two papers shouldn't be that large)

Thanks.

**Comment by HobbitLong** [comment]
It may be reasons related to data augmentation, network architecture, etc. Also we used a logistic regression classifier.

I did not carefully read their details so maybe I missed something.

**Comment by George0726** [comment]
Thanks!
